sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmiadmimbr.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmiadmistat.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmiapartdong.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmiapartlfno.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmiapp_blk_aptinfo.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmiapp_blk_pophous.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmibank.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmibankshop.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmiblkpophous.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmibusstop.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmibusstopcnt.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmihousid.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmimprspoi.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmipophous.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmiretail.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmiretailshop.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmischool.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmiscreen.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmistore.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmisubway.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbmisubwayentr.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbwadmictydong.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbwgcrmctyrgn.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbwlgctydong.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbwmegacty.sql
sqlplus ******/******  @/home/openmate/data/spool/bcmi/sql/tbwthirdadmicty.sql

